server:
  port: 8085

spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #urls minusculas
      routes:


eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
